### ISSUE TITLE
[TypeScript Strict] Wave 1.2: Fix TypeScript errors in lib utilities and api helpers

### ISSUE THREAD

**Issue by Bharath314** [meshery/meshery#21711]
> [!NOTE]
> **WORK IN PROGRESS** 🚧
> This issue is currently being drafted or investigated. Content may change frequently, and it is not yet ready for review or assignment. Please do not ask to be assigned.

## [TypeScript Strict] Wave 1.2: Fix TypeScript errors in lib utilities and api helpers

**Epic:** #21694  

**Scope:** `lib/**/*.ts*`, `api/**/*.ts*`
**Baseline:** `70 errors across 16 files`

### Prerequisites

- [ ] Preceding wave / dependency issues merged to master
- [ ] Latest master branch pulled

### Acceptance Criteria

- [ ] All TypeScript strict errors in scope fixed
- [ ] No new `any` types introduced
- [ ] No `@ts-ignore` comments (`@ts-expect-error` permitted only with linked tracking issue)
- [ ] No non-null assertions (`!`) for null safety — use defensive runtime checks
- [ ] Commits signed with `git commit -s`

### Verification Command

```bash
cd ui
# Add lib/**/*.ts*, api/**/*.ts* to tsconfig.strict.json include, then:
./node_modules/.bin/tsc -p tsconfig.strict.json --noEmit
```

### Error Breakdown

| Error Code | Count | Description | Fix Strategy |
|---|---|---|---|
| TS2532 | 26 | Object is possibly `undefined` or `null` | Add null checks or defensive guards |
| TS2345 | 24 | Argument type mismatch | Type arguments correctly or cast to correct type |
| TS2322 | 11 | Type incompatibility | Align types or add proper type annotations |
| TS18048 | 4 | Property is possibly `undefined` | Check property existence before access |
| TS2578 | 2 | Unused `@ts-expect-error` | Remove directive or link to tracking issue |
| TS2339 | 2 | Property does not exist on type | Add missing property or fix type definition |
| TS2353 | 1 | Object literal with unknown property | Remove unknown property or extend type |

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://meshery.io/community#handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
- 📺 [Self-paced Contributor Trainings](https://meshery.io/talks-and-trainings#trainings)

**Comment by VanshikaSabharwal** [comment]
@Bharath314 I would like to fix this issue

**Comment by KDeekshita** [comment]
hi @Bharath314 i want to contribute to this can u assign me if its open

**Comment by iakshkhurana** [comment]
Hi @Bharath314, I'd like to work on Wave 1.2 (lib utilities and api helpers). Could you please assign this to me?
